services:
  ollama:
    container_name: ollama
    image: ollama/ollama
    volumes:
      - ./.ollama:/root/.ollama
    network_mode: host
    ports:
      - 11434:11434
    environment:
      - OLLAMA_DEBUG=1
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu

  open-webui:
    network_mode: host
    # ports:
    #     - 3000:8080
    environment:
      - OLLAMA_BASE_URL=http://127.0.0.1:11434
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu
    volumes:
      # - .ollama:/root/.ollama
      - open-webui:/app/backend/data
    container_name: open-webui
    # restart: always
    image: ghcr.io/open-webui/open-webui:main

volumes:
    ollama:
        external: true
        name: ollama
    open-webui:
        external: true
        name: open-webui